### ISSUE TITLE
Upscaling frames with slightly higher resolution

### ISSUE THREAD

**Issue by mehranjeelani** [XinyiYing/D3Dnet#20]
how to run this for videos with high resolution? When I test on Vid4 dataset it works fine (180x144 resolution) but when I test it on my own dataset (640x360)) resolution, it shows **RuntimeError: CUDA error: an illegal memory access was encountered** which is actually due to out of GPU memory (16 GB GPU memory). Is there a way to fix this? I am also pasting the stack trace:
Traceback (most recent call last):
  File "test.py", line 139, in <module>
    main(dataset)
  File "test.py", line 129, in main
    Klens_demo_test(net, test_loader, opt.scale_factor, dataset_name)
  File "test.py", line 68, in Klens_demo_test
    SR = net(LR)
  File "/data3/conda/envs/mehran/pythonlatest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/superresolution/video_sr/D3Dnet/code/model.py", line 47, in forward
    out = self.residual_layer(out)
  File "/data3/conda/envs/mehran/pythonlatest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data3/conda/envs/mehran/pythonlatest/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/data3/conda/envs/mehran/pythonlatest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/superresolution/video_sr/D3Dnet/code/model.py", line 64, in forward
    return self.dcn1(self.lrelu(self.dcn0(x))) + x
  File "/data3/conda/envs/mehran/pythonlatest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/superresolution/video_sr/D3Dnet/code/dcn/modules/deform_conv.py", line 287, in forward
    self.im2col_step)
  File "/data2/superresolution/video_sr/D3Dnet/code/dcn/functions/deform_conv_func.py", line 34, in forward
    ctx.im2col_step)
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by XinyiYing** [comment]
We suggest the reader for the following probable solutions:
1. Reduce the input batch size.
2. Crop the whole image into overlapped patches and fed them to D3Dnet. Afterwards, recombine the output patches into an SR image.
3. Buy larger GPU.
